# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mymain.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1151, 800)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 1191, 800))
        self.frame_2.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(160, 0, 1031, 800))
        self.frame_3.setStyleSheet("QFrame{\n"
"    background-color: rgb(237, 235, 235);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.performance = QtWidgets.QFrame(self.frame_3)
        self.performance.setGeometry(QtCore.QRect(30, 20, 351, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.performance.sizePolicy().hasHeightForWidth())
        self.performance.setSizePolicy(sizePolicy)
        self.performance.setStyleSheet("QFrame{\n"
"    background-color: rgb(12, 20, 36);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.performance.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.performance.setFrameShadow(QtWidgets.QFrame.Raised)
        self.performance.setObjectName("performance")
        self.label_9 = QtWidgets.QLabel(self.performance)
        self.label_9.setGeometry(QtCore.QRect(60, 10, 251, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("QLabel{font-size:34px;\n"
"color:rgb(255,255,255);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.performance)
        self.label_10.setGeometry(QtCore.QRect(60, 140, 61, 41))
        self.label_10.setStyleSheet("QLabel{font-size:15px;\n"
"color:rgb(210,210,210);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.performance)
        self.label_11.setGeometry(QtCore.QRect(240, 140, 61, 41))
        self.label_11.setStyleSheet("QLabel{font-size:15px;\n"
"color:rgb(210,210,210);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_11.setObjectName("label_11")
        self.study_data = QtWidgets.QLabel(self.performance)
        self.study_data.setGeometry(QtCore.QRect(60, 80, 101, 61))
        self.study_data.setStyleSheet("QLabel{\n"
"font-size:30px;\n"
"color:rgb(240,240,240);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.study_data.setObjectName("study_data")
        self.rest_data = QtWidgets.QLabel(self.performance)
        self.rest_data.setGeometry(QtCore.QRect(230, 80, 111, 61))
        self.rest_data.setStyleSheet("QLabel{\n"
"font-size:30px;\n"
"color:rgb(240,240,240);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.rest_data.setObjectName("rest_data")
        self.time_label = QtWidgets.QLabel(self.performance)
        self.time_label.setGeometry(QtCore.QRect(100, 170, 241, 111))
        self.time_label.setStyleSheet("QLabel{font-size:40px;\n"
"color:rgb(255,255,255);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.time_label.setObjectName("time_label")
        self.status_label = QtWidgets.QLabel(self.performance)
        self.status_label.setGeometry(QtCore.QRect(50, 250, 271, 111))
        self.status_label.setStyleSheet("QLabel{font-size:30px;\n"
"color:rgb(255,255,255);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.status_label.setObjectName("status_label")
        self.label_12 = QtWidgets.QLabel(self.performance)
        self.label_12.setGeometry(QtCore.QRect(350, 230, 251, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("QLabel{font-size:34px;\n"
"color:rgb(25,25,25);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_12.setObjectName("label_12")
        self.performance_chart = QtWidgets.QFrame(self.frame_3)
        self.performance_chart.setGeometry(QtCore.QRect(400, 20, 571, 391))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.performance_chart.sizePolicy().hasHeightForWidth())
        self.performance_chart.setSizePolicy(sizePolicy)
        self.performance_chart.setStyleSheet("QFrame{\n"
"    background-color: rgb(149, 206, 217);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.performance_chart.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.performance_chart.setFrameShadow(QtWidgets.QFrame.Raised)
        self.performance_chart.setObjectName("performance_chart")
        self.frame_4 = QtWidgets.QFrame(self.performance_chart)
        self.frame_4.setGeometry(QtCore.QRect(10, 80, 551, 301))
        self.frame_4.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_13 = QtWidgets.QLabel(self.performance_chart)
        self.label_13.setGeometry(QtCore.QRect(30, 10, 111, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("QLabel{font-size:34px;\n"
"color:rgb(25,25,25);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.performance_chart)
        self.label_14.setGeometry(QtCore.QRect(120, 10, 161, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("QLabel{font-size:20px;\n"
"color:rgb(150,150,150);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_14.setObjectName("label_14")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(30, 460, 941, 321))
        self.frame.setStyleSheet("QFrame{\n"
"    background-color: rgb(215, 187, 167);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.frame_5 = QtWidgets.QFrame(self.frame)
        self.frame_5.setGeometry(QtCore.QRect(200, 90, 171, 181))
        self.frame_5.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.time_data = QtWidgets.QLabel(self.frame_5)
        self.time_data.setGeometry(QtCore.QRect(10, 40, 141, 131))
        self.time_data.setStyleSheet("QLabel{font-size:15px;\n"
"color:rgb(15,15,15);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.time_data.setWordWrap(True)
        self.time_data.setObjectName("time_data")
        self.frame_6 = QtWidgets.QFrame(self.frame)
        self.frame_6.setGeometry(QtCore.QRect(390, 90, 161, 181))
        self.frame_6.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.noise_data = QtWidgets.QLabel(self.frame_6)
        self.noise_data.setGeometry(QtCore.QRect(10, 45, 141, 121))
        self.noise_data.setStyleSheet("QLabel{font-size:12px;\n"
"color:rgb(20,20,20);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.noise_data.setWordWrap(True)
        self.noise_data.setObjectName("noise_data")
        self.frame_7 = QtWidgets.QFrame(self.frame)
        self.frame_7.setGeometry(QtCore.QRect(570, 90, 161, 181))
        self.frame_7.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.study_screen_data_ = QtWidgets.QLabel(self.frame_7)
        self.study_screen_data_.setGeometry(QtCore.QRect(10, 40, 141, 121))
        self.study_screen_data_.setStyleSheet("QLabel{font-size:12px;\n"
"color:rgb(25,25,25);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.study_screen_data_.setTextFormat(QtCore.Qt.AutoText)
        self.study_screen_data_.setWordWrap(True)
        self.study_screen_data_.setObjectName("study_screen_data_")
        self.frame_9 = QtWidgets.QFrame(self.frame)
        self.frame_9.setGeometry(QtCore.QRect(750, 90, 161, 181))
        self.frame_9.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:30px\n"
"}")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.label_22 = QtWidgets.QLabel(self.frame_9)
        self.label_22.setGeometry(QtCore.QRect(20, 42, 131, 121))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setStyleSheet("QLabel{font-size:15px;color:rgb(20,20,20);font-family : \'微软雅黑\';}")
        self.label_22.setScaledContents(True)
        self.label_22.setObjectName("label_22")
        self.frame_13 = QtWidgets.QFrame(self.frame)
        self.frame_13.setGeometry(QtCore.QRect(230, 60, 61, 61))
        self.frame_13.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"\n"
"    background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.frame_13.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.label_15 = QtWidgets.QLabel(self.frame_13)
        self.label_15.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.label_15.setText("")
        self.label_15.setObjectName("label_15")
        self.frame_14 = QtWidgets.QFrame(self.frame)
        self.frame_14.setGeometry(QtCore.QRect(410, 60, 61, 61))
        self.frame_14.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"\n"
"    background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.frame_14.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setGeometry(QtCore.QRect(0, 0, 81, 61))
        self.frame_15.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"\n"
"    background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.frame_15.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.label_17 = QtWidgets.QLabel(self.frame_15)
        self.label_17.setGeometry(QtCore.QRect(0, 0, 41, 41))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.frame_16 = QtWidgets.QFrame(self.frame)
        self.frame_16.setGeometry(QtCore.QRect(590, 60, 61, 61))
        self.frame_16.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"\n"
"    background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.frame_16.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.frame_17 = QtWidgets.QFrame(self.frame_16)
        self.frame_17.setGeometry(QtCore.QRect(0, 0, 81, 61))
        self.frame_17.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"\n"
"    background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.frame_17.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.label_18 = QtWidgets.QLabel(self.frame_17)
        self.label_18.setGeometry(QtCore.QRect(0, 0, 71, 71))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.frame_18 = QtWidgets.QFrame(self.frame)
        self.frame_18.setGeometry(QtCore.QRect(770, 60, 61, 61))
        self.frame_18.setStyleSheet("QFrame{\n"
"padding:8px;\n"
"\n"
"    background-color: rgb(255, 81, 45);\n"
"border:0px solid red;\n"
"border-radius:10px\n"
"}")
        self.frame_18.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.label_19 = QtWidgets.QLabel(self.frame_18)
        self.label_19.setGeometry(QtCore.QRect(0, 0, 61, 61))
        self.label_19.setText("")
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(30, 10, 111, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setStyleSheet("QLabel{font-size:25px;\n"
"color:rgb(50,50,50);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.frame)
        self.label_21.setGeometry(QtCore.QRect(30, 90, 111, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        self.label_21.setFont(font)
        self.label_21.setStyleSheet("QLabel{font-size:15px;\n"
"color:rgb(50,50,50);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.label_21.setObjectName("label_21")
        self.stop_button = QtWidgets.QPushButton(self.frame_2)
        self.stop_button.setGeometry(QtCore.QRect(10, 570, 142, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.stop_button.setFont(font)
        self.stop_button.setStyleSheet("\n"
"color: rgb(55,55,55);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/svg/img/svg/对号1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stop_button.setIcon(icon)
        self.stop_button.setIconSize(QtCore.QSize(24, 24))
        self.stop_button.setObjectName("stop_button")
        self.start_button = QtWidgets.QPushButton(self.frame_2)
        self.start_button.setGeometry(QtCore.QRect(10, 503, 144, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.start_button.setFont(font)
        self.start_button.setStyleSheet("")
        icon = QtGui.QIcon.fromTheme("accessories-calculator")
        self.start_button.setIcon(icon)
        self.start_button.setIconSize(QtCore.QSize(24, 24))
        self.start_button.setObjectName("start_button")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 700, 100, 40))
        self.pushButton_4.setStyleSheet("color: rgb(50,50,50);\n"
"border:none;\n"
"text-align:left;\n"
"padding:12px;")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/buttom/img/buttom/退出文件夹_folder-withdrawal.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_4.setIcon(icon1)
        self.pushButton_4.setObjectName("pushButton_4")
        self.user_name_label = QtWidgets.QLabel(self.frame_2)
        self.user_name_label.setGeometry(QtCore.QRect(20, 170, 121, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(-1)
        font.setBold(True)
        self.user_name_label.setFont(font)
        self.user_name_label.setStyleSheet("QLabel{font-size:20px;\n"
"color:rgb(50,50,50);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.user_name_label.setObjectName("user_name_label")
        self.touxiang = QtWidgets.QLabel(self.frame_2)
        self.touxiang.setGeometry(QtCore.QRect(23, 50, 101, 111))
        self.touxiang.setStyleSheet("QLabel{font-size:30px;\n"
"color:rgb(0,0,0);\n"
"font-family : \'微软雅黑\';\n"
"}")
        self.touxiang.setText("")
        self.touxiang.setObjectName("touxiang")
        self.log_out = QtWidgets.QPushButton(self.frame_2)
        self.log_out.setGeometry(QtCore.QRect(10, 640, 142, 41))
        font = QtGui.QFont()
        font.setBold(True)
        self.log_out.setFont(font)
        self.log_out.setStyleSheet("\n"
"color: rgb(55,55,55);")
        self.log_out.setIcon(icon)
        self.log_out.setIconSize(QtCore.QSize(24, 24))
        self.log_out.setObjectName("log_out")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_9.setText(_translate("Form", "Performance"))
        self.label_10.setText(_translate("Form", "study"))
        self.label_11.setText(_translate("Form", "rest"))
        self.study_data.setText(_translate("Form", "0%"))
        self.rest_data.setText(_translate("Form", "0%"))
        self.time_label.setText(_translate("Form", "00:00:00"))
        self.status_label.setText(_translate("Form", "now:     computer"))
        self.label_12.setText(_translate("Form", "Performance"))
        self.label_13.setText(_translate("Form", "data"))
        self.label_14.setText(_translate("Form", "study&noise"))
        self.time_data.setText(_translate("Form", "the data of time"))
        self.noise_data.setText(_translate("Form", "the data of noise"))
        self.study_screen_data_.setText(_translate("Form", "the specific use of time"))
        self.label_22.setText(_translate("Form", "the suggestions"))
        self.label_20.setText(_translate("Form", "result"))
        self.label_21.setText(_translate("Form", "报告尚未生成"))
        self.stop_button.setText(_translate("Form", "end"))
        self.start_button.setText(_translate("Form", "start "))
        self.pushButton_4.setText(_translate("Form", "Exit"))
        self.user_name_label.setText(_translate("Form", "lzt_tzl"))
        self.log_out.setText(_translate("Form", "log out"))

